# Generated by Django 2.0.2 on 2018-04-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0002_auto_20180412_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chien',
            name='proprio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiens', to='DoggyBook.Proprietaire'),
        ),
        migrations.AlterField(
            model_name='chien',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiens', to='DoggyBook.Race'),
        ),
    ]
