# Generated by Django 2.0.2 on 2018-04-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0004_auto_20180412_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chien',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='chien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='DoggyBook.Chien'),
        ),
    ]
