# Generated by Django 2.0.3 on 2018-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0005_auto_20180413_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='chien',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='model_pic',
            field=models.ImageField(default='DoggyBook/Dog/media/photos/chien/dogo5.jpeg', upload_to='pic_folder/'),
        ),
    ]
