# Generated by Django 2.0.4 on 2018-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0001_initial'),
    ]

    operations = [
    ]
