# Generated by Django 2.0.2 on 2018-04-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DoggyBook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='prenom',
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='telephone',
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='user',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
