# Generated by Django 2.0.2 on 2018-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0002_auto_20180525_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='avis',
            field=models.TextField(blank=True),
        ),
    ]
