# Generated by Django 2.0.2 on 2018-05-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0003_photo_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='avis',
        ),
    ]
