# Generated by Django 2.0.5 on 2018-05-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0004_remove_photo_avis'),
        ('DoggyBook', '0002_auto_20180525_1720'),
    ]

    operations = [
    ]
