# Generated by Django 2.0.3 on 2018-05-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0002_auto_20180525_1720'),
        ('DoggyBook', '0004_remove_photo_avis'),
    ]

    operations = [
    ]
