# Generated by Django 2.0.5 on 2018-05-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0005_merge_20180528_1438'),
        ('DoggyBook', '0006_auto_20180527_2347'),
    ]

    operations = [
    ]
