# Generated by Django 2.0.2 on 2018-05-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0005_merge_20180528_1438'),
        ('DoggyBook', '0006_auto_20180527_2347'),
    ]

    operations = [
    ]
