# Generated by Django 2.0.3 on 2018-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0007_auto_20180419_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='photo_profil',
            field=models.ImageField(blank=True, upload_to='photos/proprio/user_id'),
        ),
    ]
