# Generated by Django 2.0.5 on 2018-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0007_merge_20180529_1457'),
        ('DoggyBook', '0007_merge_20180529_1244'),
    ]

    operations = [
    ]
