# Generated by Django 2.0.3 on 2018-05-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0007_merge_20180529_1457'),
        ('DoggyBook', '0007_merge_20180529_1345'),
    ]

    operations = [
    ]
