# Generated by Django 2.0.3 on 2018-05-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0007_merge_20180529_1244'),
        ('DoggyBook', '0008_merge_20180529_1705'),
    ]

    operations = [
    ]
