# Generated by Django 2.0.5 on 2018-05-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0009_merge_20180529_1756'),
        ('DoggyBook', '0008_merge_20180529_1738'),
        ('DoggyBook', '0005_merge_20180529_1933'),
    ]

    operations = [
    ]
