# Generated by Django 2.0.3 on 2018-05-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0008_merge_20180529_1738'),
        ('DoggyBook', '0009_merge_20180529_1756'),
    ]

    operations = [
    ]
