# Generated by Django 2.0.2 on 2018-05-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0010_merge_20180529_2010'),
        ('DoggyBook', '0010_merge_20180529_2144'),
    ]

    operations = [
    ]
