# Generated by Django 2.0.5 on 2018-05-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0010_merge_20180529_2144'),
        ('DoggyBook', '0010_merge_20180529_2010'),
    ]

    operations = [
    ]
