# Generated by Django 2.0.5 on 2018-05-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0012_rental'),
        ('DoggyBook', '0011_merge_20180530_0014'),
    ]

    operations = [
    ]
