# Generated by Django 2.0.5 on 2018-05-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoggyBook', '0010_merge_20180530_0127'),
        ('DoggyBook', '0013_merge_20180530_0103'),
    ]

    operations = [
    ]
